services:
  server:
    build: ./backend
    #image: wildshare-backend:latest
    platform: linux/amd64
    volumes:
      - ./upload:/app/upload
      - ./upload/avatar:/app/upload/avatar
      - ./upload/ressources:/app/upload/ressources
      - ./upload/ressourcesImages:/app/upload/ressourcesImages
    env_file:
      - .env

  front:
    build: ./frontend
    #image: wildshare-frontend:latest
    platform: linux/amd64

  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer
    platform: linux/amd64

  nginx:
    image: nginx:1.21.3
    platform: linux/amd64
    depends_on:
      - server
      - front
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env

volumes:
  pgdata:
