import Head from "next/head";
import Header from "./header";

export type LayoutProps = {
  title: string;
  children: React.ReactNode;
};

export default function Layout(props: LayoutProps): React.ReactNode {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main-content">{props.children}</main>
    </>
  );
}
